version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:30"
    reviewers:
      - "jpbernius"
    open-pull-requests-limit: 2
